packages:
  - .

nodeLinker: hoisted
autoInstallPeers: true
minimumReleaseAgeExclude:
  - '@dsh-mermaid-renderer/dsh-client-modules@0.1.0-rc.6-mermaid.10'
  - '@dsh-mermaid-renderer/dsh-client-ui-conversation@0.1.0-rc.6-mermaid.10'
  - '@dsh-mermaid-renderer/dsh-client-ui-mermaid@0.1.0-rc.6-mermaid.10'
  - '@dsh-mermaid-renderer/dsh-client-ui-primitives@0.1.0-rc.6-mermaid.10'
  - '@dsh-mermaid-renderer/dsh-web-app-mermaid@0.1.0-rc.6-mermaid.10'
  - '@dsh-mermaid-renderer/dsh-web-frontend@0.1.0-rc.6-mermaid.10'
  - ''
allowBuilds:
  koffi: true
  esbuild: true
  '@deepseek-ai/dsh-subprocess-local': set this to true or false
  '@google/genai': set this to true or false
  node-pty: set this to true or false
  protobufjs: set this to true or false
networkConcurrency: 2
fetchRetries: 20
fetchRetryMaxtimeout: 60000
fetchTimeout: 600000
